### PR TITLE
Fix for MW 1.31 and SMW 3.*

### PR DESCRIPTION
**Pull request by PeterTheOne**
Tested with the following markup which triggers an email notification on 2019-04-25T10:00:00Z when the cronjob runs:
```
[[Assigned to::User:Admin]]
[[Reminder at::2019-04-25T10:00:00Z]]
[[Target date::2019-04-25T10:00:00Z]]
[[Status::In Progress]]
```

Also when setting `[[Assigned to::User:Admin]]` an E-Mail is sent to the Admin User immediately.

This PR mostly replaces deprecated function calls.

@krabina please check if it works on your setup or provide me with Wiki markup that you use for your tasks that should get an email notification. So that I can test it more.

### CODE REVIEW

**Comment by krabina** [comment]
I just tested it and it works. should be merged to master so others can test it too.

**Comment by kghbln** [comment]
@krabina I have installed this extension on "sandbox" and an example/public test can now be set up. Please add the respective pages to the [respective category](https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:Semantic_Tasks_example). Thanks a ton!

**Comment by krabina** [comment]
hmm. Does not seem to send e-mail from sandbox...

**Comment by kghbln** [comment]
I am not sure what is supposed to happen from what you added to the wiki. The wiki as such sends out e-mails and I get #8 notes via cron. So it appears that the script is at least trying to do something. Perhaps it is failing because the wiki uses Elasticsearch as backend, though I do not think this should be an issue.

**Comment by kghbln** [comment]
Obviously removing stuff from a page triggers immediate notifications. At least I go one form [this edit](https://sandbox.semantic-mediawiki.org/w/index.php?title=Cat%C3%A9gorie:Semantic_Tasks_example&diff=14598&oldid=14593)

**Comment by krabina** [comment]
great so it works. I didn't get anything, but you don't get notifications for your own edits...

**Comment by kghbln** [comment]
I am afraid it does not. At least this is how it appears to me. This notification was triggered by my own edit which was clearing the page. Why shouldn't you get a notification? Still I have no idea who is supposed to be getting what.

**Comment by krabina** [comment]
As soon as your user is annotated in the Assigned to or Carbon copy property, you should get an email with a diff. But not if it was your own edit or a minor edit.

**Pull request merged**
